version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /c/Users/acer/Desktop/applcrda/app/monitoring/prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /c/Users/acer/Desktop/applcrda/app/monitoring/datasources.yml:/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
