apiVersion: apps/v1
kind: Deployment
metadata:
  name: enregistrement-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enregistrement
  template:
    metadata:
      labels:
        app: enregistrement
    spec:
      containers:
      - name: enregistrement
        image: votre_nom_d'utilisateur/mon-application-enregistrement:latest
        ports:
        - containerPort: 3002
        resources:
          limits:
            memory: "256Mi" # Limite de mémoire à 256 MiB
            cpu: "500m"     # Limite de CPU à 0.5 unité (500 milli-CPU)
          requests:
            memory: "128Mi" # Demande de mémoire de 128 MiB
            cpu: "250m"     # Demande de CPU de 0.25 unité (250 milli-CPU)
