apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "base_crda"
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        livenessProbe:
          exec:
            command:
              - mysqladmin
              - ping
              - "-uapp_user"
              - "-p$(MYSQL_PASSWORD)"
          initialDelaySeconds: 45
          periodSeconds: 15