apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: crda-namespace
spec:
  selector:
    app: mysql
    tier: database
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None