apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: crda-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crda-app
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crda-app
        tier: backend
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: crda-app
        image: najwa22/crda-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql-service.crda-namespace.svc.cluster.local"
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5