apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: crda-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crda-app
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crda-app
        tier: backend
    spec:
      initContainers:
      - name: check-mysql
        image: busybox:1.35
        command: ['sh', '-c', 
          'until nc -zv mysql-service.crda-namespace.svc.cluster.local 3306; do echo "Waiting for MySQL"; sleep 2; done']
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: crda-app
        image: najwa22/crda-app:75  # Pinned version
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql-service.crda-namespace.svc.cluster.local"
        - name: MYSQL_USER
          value: "app_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 8