apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: crda-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crda-app
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    spec:
      initContainers:
      - name: db-check
        image: busybox:1.35
        command: ['sh', '-c', 
          'until nc -zw 2 mysql-service 3306; do echo "Waiting for DB"; sleep 2; done']
      containers:
      - name: app
        image: najwa22/crda-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15