apiVersion: apps/v1
kind: Deployment
metadata:
  name: crda-app
spec:
  selector:
    matchLabels:
      app: crda-app
  template:
    metadata:
      labels:
        app: crda-app
    spec:
      containers:
      - name: crda-app
        image: najwa22/crda-app:IMAGE_TAG
        ports:
        - containerPort: 4200
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"