apiVersion: apps/v1
kind: Deployment
metadata:
  name: crda-app
spec:
  selector:
    matchLabels:
      app: crda-app
  template:
    metadata:
      labels:
        app: crda-app
    spec:
      containers:
      - name: app
        image: najwa22/crda-app:BUILD_ID
        ports:
        - containerPort: 4200
        env:
        - name: MYSQL_HOST
          value: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: crda-service
spec:
  type: LoadBalancer
  selector:
    app: crda-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200