apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: crda-app
  replicas: 2
  template:
    metadata:
      labels:
        app: crda-app
    spec:
      imagePullSecrets:
      - name: dockerhub-credentials
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting for MySQL"; sleep 5; done']
      containers:
      - name: crda-app
        image: najwa22/crda-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: crda-service
spec:
  type: LoadBalancer
  selector:
    app: crda-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200