apiVersion: apps/v1
kind: Deployment
metadata:
  name: crda-app
spec:
  selector:
    matchLabels:
      app: crda-app
  template:
    metadata:
      labels:
        app: crda-app
    spec:
      containers:
      - name: crda-app
        image: najwa22/crda-app:IMAGE_TAG  # Will be replaced by Jenkins
        ports:
        - containerPort: 4200
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
---
apiVersion: v1
kind: Service
metadata:
  name: crda-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4200
  selector:
    app: crda-app