---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS base_crda;
    USE base_crda;
    -- Table structure for rapport
    CREATE TABLE `rapport` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `nom` varchar(255) NOT NULL,
      `prenom` varchar(255) NOT NULL,
      `cin` varchar(50) NOT NULL,
      `sujet` text NOT NULL,
      `surface` decimal(10,2) NOT NULL,
      `limites_terrain` text NOT NULL,
      `localisation` varchar(255) NOT NULL,
      `superficie_batiments_anciens` decimal(10,2) NOT NULL,
      `observations` text DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_cin_sujet` (`cin`,`sujet`),
      KEY `idx_cin` (`cin`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    -- Table structure for results
    CREATE TABLE `results` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `sujet` varchar(255) NOT NULL,
      `nom` varchar(255) NOT NULL,
      `prenom` varchar(255) NOT NULL,
      `cin` varchar(255) NOT NULL,
      `numero_transaction` varchar(255) NOT NULL,
      `statut` enum('بصدد الدرس','مقبول','مرفوض') NOT NULL DEFAULT 'بصدد الدرس',
      PRIMARY KEY (`id`),
      UNIQUE KEY `unique_service` (`cin`,`sujet`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    -- Table structure for services_utilisateur
    CREATE TABLE `services_utilisateur` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `prenom` varchar(255) DEFAULT NULL,
      `nom` varchar(255) DEFAULT NULL,
      `cin` varchar(255) DEFAULT NULL,
      `numero_transaction` varchar(255) DEFAULT NULL,
      `certificat_propriete_terre` tinyint(1) DEFAULT NULL,
      `copie_piece_identite_fermier` tinyint(1) DEFAULT NULL,
      `copie_piece_identite_nationale` tinyint(1) DEFAULT NULL,
      `demande_but` tinyint(1) DEFAULT NULL,
      `copie_contrat_location_terrain` tinyint(1) DEFAULT NULL,
      `autres_documents` tinyint(1) DEFAULT NULL,
      `sujet` varchar(255) DEFAULT NULL,
      `status` varchar(255) NOT NULL DEFAULT 'قيد الانتظار',
      PRIMARY KEY (`id`),
      KEY `idx_cin` (`cin`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    -- Table structure for utilisateur
    CREATE TABLE `utilisateur` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `nom_user` varchar(100) NOT NULL,
      `prenom_user` varchar(100) NOT NULL,
      `sex_user` enum('homme','femme') NOT NULL,
      `cin_user` varchar(15) NOT NULL,
      `email_user` varchar(255) NOT NULL,
      `password_user` varchar(255) NOT NULL,
      `role_user` enum('directeur','gerant','chef_dentreprise','pending') NOT NULL,
      `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
      `status_user` enum('pending','approved','rejected') DEFAULT 'pending',
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

    -- Indexes
    ALTER TABLE `rapport` ADD FULLTEXT KEY `idx_sujet` (`sujet`);