apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentification
  template:
    metadata:
      labels:
        app: authentification
    spec:
      containers:
        - name: authentification
          image: najwakarrouchi968/authentification:version4
          ports:
            - containerPort: 3001
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: example
            - name: MYSQL_DB
              value: auth_db
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: authentification
spec:
  selector:
    app: authentification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
